"Compatability to ViM (not Vi)
set nocompatible

"Disable automatic nextline commenting
autocmd FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

"For easy editing of config
let $RTP = split(&runtimepath, ',')[0]
let $RC = "$HOME/.vim/vimrc"

"leaders
let mapleader = ";"
"must escape backslash
let maplocalleader = "\\"

"Enable filetype detection, plugins and indents
filetype plugin indent on

"Plugin setup
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin('~/.vim/plugged')

"Tmux config
Plug 'christoomey/vim-tmux-navigator'

call plug#end()

"Enable syntax highlighting
syntax on
set background=dark "Use default style with dark background

set timeoutlen=1000 "Delay in ms to time out on a mapping
set ttimeoutlen=50 "Delay in ms to time out on individual keypress

"Make backspaces normal
set backspace=indent,eol,start

"Set tabs to 'python' style by default
setlocal shiftwidth=4 tabstop=4 softtabstop=4 expandtab autoindent smartindent

"Allow leaving buffer without saving
set hidden
set noswapfile
set showcmd

"Set path to current directory and all subdirectories recursively
"Makes find command effective
set path=.,**

"Search configuration
set ignorecase smartcase incsearch hlsearch

"show line numbers - relative for all lines except current line
set number
set relativenumber 

set encoding=utf-8

"STATUS BAR
"Always display statusbar
set laststatus=2

"SPLITS
"Splits open at bottom and right 
set splitbelow 
set splitright
"shortcut split navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

"terminal mode same mappings
tnoremap <C-h> <C-w>h
tnoremap <C-j> <C-w>j
tnoremap <C-k> <C-w>k
tnoremap <C-l> <C-w>l

"Toggle syntax highlighting of current search off
nnoremap <CR> :nohlsearch<CR><CR>

